//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 25. 11:07:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using Microsoft;
//using Microsoft.VisualBasic.ApplicationServices;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using vizualis_beadando.Data;
using vizualis_beadando;

namespace Model
{
    public partial class Felhasznalo {

        [Key]
        public long f_id { get; set; }

        public string felhasznalo_n { get; set; }

        public long f_kedvenc_id { get; set; }

        public long s_kedvenc_id { get; set; }

        public long t_kedvenc_id { get; set; }

        public long Foetelekf_id { get; set; }

        public long s_id { get; set; }

        public long t_id { get; set; }

        public long fe_id { get; set; }

        public virtual Sutemenyek Sutemenyek { get; set; }

        public virtual Tortak Tortak { get; set; }

        public virtual Foetelek Foetelek { get; set; }
      
  
    }

}
