//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 25. 11:07:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Model
{
    public partial class Foetelek {

        public Foetelek()
        {
            this.Felhasznalok = new List<Felhasznalo>();
            OnCreated();
        }

        [Key]
        public long f_id { get; set; }

        public string nev { get; set; }

        public long chef_id { get; set; }

        public long c_id { get; set; }

        public virtual Chef Chef { get; set; }

        public virtual IList<Felhasznalo> Felhasznalok { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
