//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 25. 11:07:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Model
{
    public partial class Chef {

        public Chef()
        {
            this.Foetelek = new List<Foetelek>();
            this.Sutemenyek = new List<Sutemenyek>();
            this.Tortak = new List<Tortak>();
            OnCreated();
        }

        [Key]
        public long c_id { get; set; }

        public string c_nev { get; set; }

        public long f_keszito { get; set; }

        public long s_keszito { get; set; }

        public long t_keszito { get; set; }

        public virtual IList<Foetelek> Foetelek { get; set; }

        public virtual IList<Sutemenyek> Sutemenyek { get; set; }

        public virtual IList<Tortak> Tortak { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
